buildscript {
    repositories {
        google()
        mavenCentral()
        // 添加 jitpack 以便下载 dotenv-android 插件
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'

    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}