apply plugin: 'com.android.application'

android {
    namespace 'com.smog.weatherapp'
    compileSdk 34

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        applicationId "com.smog.weatherapp"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
        buildConfigField "String", "BACK_HOST_API", "\"http://10.198.168.115:8080/api/\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.github.AnyChart:AnyChart-Android:1.1.2'
}